name = "CellMLModelRepository"
uuid = "44f94207-8466-4895-823f-594c0355a39c"
authors = ["Anand <anandj@uchicago.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
